
export const POST_CREATEUSER_SUCCESS = "POST_CREATEUSER_SUCCESS";
 export const POST_CREATEUSER_ERROR = "POST_CREATEUSER_ERROR";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";

